# Generated by Django 2.0.8 on 2018-09-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_use_condition',
            name='booker_email',
            field=models.EmailField(max_length=30, verbose_name='訂房人電子信箱'),
        ),
        migrations.AlterField(
            model_name='room_use_condition',
            name='booker_name',
            field=models.CharField(max_length=25, verbose_name='訂房人姓名'),
        ),
        migrations.AlterField(
            model_name='room_use_condition',
            name='booker_phone',
            field=models.CharField(max_length=20, verbose_name='訂房人電話號碼'),
        ),
        migrations.AlterField(
            model_name='room_use_condition',
            name='booking_time',
            field=models.DateTimeField(verbose_name='訂房時間'),
        ),
        migrations.AlterField(
            model_name='room_use_condition',
            name='confirmed_time',
            field=models.DateTimeField(verbose_name='確認時間'),
        ),
    ]
