# Generated by Django 2.0.8 on 2018-09-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180913_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=15, verbose_name='誰')),
                ('message', models.CharField(max_length=300, verbose_name='說啥')),
                ('ask_time', models.DateTimeField(auto_now=True, verbose_name='詢問時間')),
                ('has_replied', models.BooleanField(default=False, verbose_name='已回覆？')),
                ('replied_message', models.CharField(default='感謝您！', max_length=300, verbose_name='回覆啥')),
                ('replied_time', models.DateTimeField(auto_now=True, verbose_name='回覆時間')),
            ],
        ),
    ]
