# Generated by Django 2.0.8 on 2018-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180928_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_message',
            name='ask_time',
            field=models.DateTimeField(verbose_name='詢問時間'),
        ),
    ]
