# Generated by Django 2.0.8 on 2018-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180928_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_message',
            name='message',
            field=models.TextField(verbose_name='說啥'),
        ),
        migrations.AlterField(
            model_name='guest_message',
            name='replied_message',
            field=models.TextField(default='感謝您！', verbose_name='回覆啥'),
        ),
    ]
