# Generated by Django 2.0.8 on 2018-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20180928_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_image_slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='首頁主照片')),
                ('image_caption', models.TextField(verbose_name='照片圖說')),
            ],
        ),
    ]
