# Generated by Django 2.0.8 on 2018-10-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_home_image_slides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home_image_slides',
        ),
    ]
