# Generated by Django 2.0.8 on 2018-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_delete_home_image_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=30, verbose_name='標題')),
                ('news_content', models.TextField(verbose_name='內容')),
                ('news_thumbnail', models.FileField(upload_to='', verbose_name='縮圖')),
                ('news_upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
