# Generated by Django 2.1.2 on 2018-10-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20181029_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name': '上傳輔助檔案', 'verbose_name_plural': '上傳輔助檔案'},
        ),
        migrations.AlterModelOptions(
            name='guest_message',
            options={'verbose_name': '顧客留言', 'verbose_name_plural': '顧客留言'},
        ),
        migrations.AlterModelOptions(
            name='nearby_dashboard',
            options={'verbose_name': '附近景點', 'verbose_name_plural': '附近景點'},
        ),
        migrations.AlterModelOptions(
            name='news_dashboard',
            options={'verbose_name': '最新消息', 'verbose_name_plural': '最新消息'},
        ),
        migrations.AlterModelOptions(
            name='price_multifier',
            options={'verbose_name': '打折設定', 'verbose_name_plural': '打折設定'},
        ),
        migrations.AlterModelOptions(
            name='room_types',
            options={'verbose_name': '房型基本資料', 'verbose_name_plural': '房型基本資料'},
        ),
        migrations.AlterModelOptions(
            name='room_use_condition',
            options={'verbose_name': '用房狀況', 'verbose_name_plural': '用房狀況'},
        ),
        migrations.RenameField(
            model_name='nearby_dashboard',
            old_name='Nearby_content',
            new_name='nearby_content',
        ),
        migrations.RenameField(
            model_name='nearby_dashboard',
            old_name='Nearby_thumbnail',
            new_name='nearby_thumbnail',
        ),
        migrations.RenameField(
            model_name='nearby_dashboard',
            old_name='Nearby_title',
            new_name='nearby_title',
        ),
        migrations.RenameField(
            model_name='nearby_dashboard',
            old_name='Nearby_upload_time',
            new_name='nearby_upload_time',
        ),
    ]
