# Generated by Django 2.1.2 on 2018-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20181029_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(verbose_name='段落')),
            ],
            options={
                'verbose_name': '客製文字段落',
                'verbose_name_plural': '客製文字段落',
            },
        ),
    ]
