# Generated by Django 2.1.2 on 2018-11-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_customtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomText',
        ),
    ]
