# Generated by Django 2.1.2 on 2018-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_delete_customtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_name', models.CharField(max_length=30, verbose_name='段落名稱')),
                ('paragraph_text', models.TextField(verbose_name='段落內容')),
            ],
            options={
                'verbose_name': '客製文字段落',
                'verbose_name_plural': '客製文字段落',
            },
        ),
    ]
