# Generated by Django 2.1.2 on 2018-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_customtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='輔助檔案名稱')),
                ('name', models.CharField(max_length=25, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '模板需求照片',
                'verbose_name_plural': '模板需求照片',
            },
        ),
    ]
